### ISSUE TITLE
Italics do not show up properly

### ISSUE THREAD

**Issue by bluebear94** [Ziphil/ZpdicOnlineNova#34]
If you use italics `*like this*` in a content field, the text doesn't show up that way.

For example:

```
Before a word that starts with a vowel, it becomes *al*. For example, *al an* means "to me".

It also becomes *al* when it is retained at the end of a relative clause. For example, *tu et ridia l'an fitat miik al* "This is Ridia, to whom I gave an apple".
```

shows up as:

![image](https://user-images.githubusercontent.com/2975203/102690888-90053800-41d6-11eb-9dc7-77bacb43c432.png)

**Comment by Ziphil** [comment]
Some markups, including italics and bolds, are not supported for stylistic reason. But ok, I will only allow italics.
