### ISSUE TITLE
編集内容がたまに見えなくなるバグ

### ISSUE THREAD

**Issue by KawaneRio** [Ziphil/ZpdicOnlineNova#95]
出現条件は不明。時間が立つと直る。謎。
ちなみに内容が見えないだけで、編集は出徠る。コピペとかで。解せぬ。

## 環境

使用ブラウザはFirefoxです。
`firefox --version`
```
Mozilla Firefox 96.0
```
その他
```
OS: Ubuntu 20.04.3 LTS (Focal Fossa)
 Kernel: 5.13.0-27-lowlatency x86_64 
CPU: 8-Core AMD Ryzen 7 5700G with Radeon Graphics (-MT MCP-)
Memory: 46.93 GiB
GPU: AMD Ellesmere [Radeon RX 580]
 v: 4.6 Mesa 22.0.0-devel (git-bdf1163 2022-01-25 focal-oibaf-ppa)
```

## スクショ

<details><summary>折り疊み〜♪</summary><div>

![スクリーンショット_2022-01-25_20-41-53](https://user-images.githubusercontent.com/61252570/150978658-013d5646-61af-48ca-902c-876c2e450307.png)

</div></details>

**Comment by Ziphil** [comment]
報告ありがとうございます。調査します。
- 対応チケット: https://ziphil.notion.site/10128985f21d4890abed66e2e870827a

**Comment by Ziphil** [comment]
ver 2.34.1 で修正しました。
